# Generated by Django 5.0 on 2024-01-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featuredImage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
