# Generated by Django 5.0 on 2024-01-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogpost_featuredimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='featuredImage',
            new_name='featured_image',
        ),
    ]
