# Generated by Django 5.0 on 2024-01-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_featuredimage_blogpost_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
